from mimesis import (Generic, Address, Person, Code, Finance, Food,
                     Choice, Datetime, Text, Internet, Science,
                     Path, Payment, Hardware, Transport, File)
from mimesis.locales import Locale

num = 10

print(f"无地区地址：{[Generic(locale=Locale.ZH).address.address() for i in range(num)]}")

print("*" * 50)

print(f"无地区地址：{[Address(locale=Locale.ZH).address() for _ in range(num)]}")
print(f"国家：{[Address(locale=Locale.ZH).country() for _ in range(num)]}")
print(f"国家代码：{[Address(locale=Locale.ZH).country_code() for _ in range(num)]}")
print(f"国家旗帜：{[Address(locale=Locale.ZH).country_emoji_flag() for _ in range(num)]}")
print(f"默认国家：{[Address(locale=Locale.ZH).default_country() for _ in range(num)]}")
print(f"州/省：{[Address(locale=Locale.ZH).state() for _ in range(num)]}")
print(f"城市：{[Address(locale=Locale.ZH).city() for _ in range(num)]}")
print(f"六位邮编：{[Address(locale=Locale.ZH).postal_code() for _ in range(num)]}")
print(f"电话区号：{[Address(locale=Locale.ZH).calling_code() for _ in range(num)]}")
print(f"大陆：{[Address(locale=Locale.ZH).continent() for _ in range(num)]}")
print(f"经纬度：{[Address(locale=Locale.ZH).coordinates() for _ in range(num)]}")
print(f"联邦主体：{[Address(locale=Locale.ZH).federal_subject() for _ in range(num)]}")
print(f"isd代码：{[Address(locale=Locale.ZH).isd_code() for _ in range(num)]}")
print(f"纬度：{[Address(locale=Locale.ZH).latitude() for _ in range(num)]}")
print(f"经度：{[Address(locale=Locale.ZH).longitude() for _ in range(num)]}")
print(f"洲：{[Address(locale=Locale.ZH).prefecture() for _ in range(num)]}")
print(f"省：{[Address(locale=Locale.ZH).province() for _ in range(num)]}")
print(f"地区：{[Address(locale=Locale.ZH).region() for _ in range(num)]}")
print(f"街道名称：{[Address(locale=Locale.ZH).street_name() for _ in range(num)]}")
print(f"街道号码：{[Address(locale=Locale.ZH).street_number() for _ in range(num)]}")
print(f"街道后缀：{[Address(locale=Locale.ZH).street_suffix() for _ in range(num)]}")
print(f"邮编：{[Address(locale=Locale.ZH).zip_code() for _ in range(num)]}")

print("*" * 50)

print(f"手机号码：{[Person(locale=Locale.ZH).telephone() for _ in range(num)]}")
print(f"邮箱：{[Person(locale=Locale.ZH).email() for _ in range(num)]}")
print(f"用户名：{[Person(locale=Locale.ZH).username() for _ in range(num)]}")
print(f"全名：{[Person(locale=Locale.ZH).full_name() for _ in range(num)]}")
print(f"名：{[Person(locale=Locale.ZH).first_name() for _ in range(num)]}")
print(f"称谓：{[Person(locale=Locale.ZH).title() for _ in range(num)]}")
print(f"名字：{[Person(locale=Locale.ZH).name() for _ in range(num)]}")
print(f"职业：{[Person(locale=Locale.ZH).occupation() for _ in range(num)]}")
print(f"性别：{[Person(locale=Locale.ZH).gender() for _ in range(num)]}")
print(f"姓：{[Person(locale=Locale.ZH).last_name() for _ in range(num)]}")
print(f"学历：{[Person(locale=Locale.ZH).academic_degree() for _ in range(num)]}")
print(f"生日日期：{[Person(locale=Locale.ZH).birthdate() for _ in range(num)]}")
print(f"血型：{[Person(locale=Locale.ZH).blood_type() for _ in range(num)]}")
print(f"性别编码：{[Person(locale=Locale.ZH).gender_code() for _ in range(num)]}")
print(f"性别符号：{[Person(locale=Locale.ZH).gender_symbol() for _ in range(num)]}")
print(f"身高：{[Person(locale=Locale.ZH).height() for _ in range(num)]}")
print(f"体重：{[Person(locale=Locale.ZH).weight() for _ in range(num)]}")
print(f"标识符：{[Person(locale=Locale.ZH).identifier() for _ in range(num)]}")
print(f"语言：{[Person(locale=Locale.ZH).language() for _ in range(num)]}")
print(f"国籍：{[Person(locale=Locale.ZH).nationality() for _ in range(num)]}")
print(f"密码：{[Person(locale=Locale.ZH).password() for _ in range(num)]}")
print(f"固定电话号码：{[Person(locale=Locale.ZH).phone_number() for _ in range(num)]}")
print(f"政治倾向：{[Person(locale=Locale.ZH).political_views() for _ in range(num)]}")
print(f"性别：{[Person(locale=Locale.ZH).sex() for _ in range(num)]}")
print(f"姓：{[Person(locale=Locale.ZH).surname() for _ in range(num)]}")
print(f"大学：{[Person(locale=Locale.ZH).university() for _ in range(num)]}")
print(f"倾向：{[Person(locale=Locale.ZH).views_on() for _ in range(num)]}")
print(f"宗教：{[Person(locale=Locale.ZH).worldview() for _ in range(num)]}")

print("*" * 50)

print(f"书号：{[Code().isbn() for _ in range(num)]}")
print(f"IMEI 条形码：{[Code().imei() for _ in range(num)]}")
print(f"语言代码：{[Code().locale_code() for _ in range(num)]}")
print(f"邮政编码 或 四位密码: {[Code().pin() for _ in range(num)]}")
print(f"EAN-13 条形码：{[Code().ean() for _ in range(num)]}")

print("*" * 50)

print(f"股票名称：{[Finance(locale=Locale.ZH).stock_name() for _ in range(num)]}")
print(f"价格：{[Finance(locale=Locale.ZH).price() for _ in range(num)]}")
print(f"区间价格：{[Finance(locale=Locale.ZH).price_in_btc(10, 50) for _ in range(num)]}")
print(f"股票代码：{[Finance(locale=Locale.ZH).stock_exchange() for _ in range(num)]}")
print(f"银行名称：{[Finance(locale=Locale.ZH).bank() for _ in range(num)]}")
print(f"公司名称：{[Finance(locale=Locale.ZH).company() for _ in range(num)]}")
print(f"公司类型：{[Finance(locale=Locale.ZH).company_type() for _ in range(num)]}")
print(f"加密货币代码：{[Finance(locale=Locale.ZH).cryptocurrency_iso_code() for _ in range(num)]}")
print(f"ISO 货币代码：{[Finance(locale=Locale.ZH).currency_iso_code() for _ in range(num)]}")
print(f"货币符号：{[Finance(locale=Locale.ZH).currency_symbol() for _ in range(num)]}")
print(f"股票行情：{[Finance(locale=Locale.ZH).stock_ticker() for _ in range(num)]}")

print("*" * 50)

print(f"主菜：{[Food(locale=Locale.ZH).dish() for _ in range(num)]}")
print(f"饮料：{[Food(locale=Locale.ZH).drink() for _ in range(num)]}")
print(f"水果：{[Food(locale=Locale.ZH).fruit() for _ in range(num)]}")
print(f"蔬菜：{[Food(locale=Locale.ZH).vegetable() for _ in range(num)]}")
print(f"香料：{[Food(locale=Locale.ZH).spices() for _ in range(num)]}")

print("*" * 50)

print(f"颜色：{[Choice().choice(['红色', '蓝色', '绿色', ]) for _ in range(num)]}")

print("*" * 50)

print(f"日期：{[Datetime().date() for _ in range(num)]}")
print(f"时间：{[Datetime().time() for _ in range(num)]}")
print(f"日期时间：{[Datetime().datetime() for _ in range(num)]}")
print(f"罗马字符世纪：{[Datetime().century() for _ in range(num)]}")
print(f"年：{[Datetime().year() for _ in range(num)]}")
print(f"月：{[Datetime().month() for _ in range(num)]}")
print(f"日：{[Datetime().day_of_month() for _ in range(num)]}")
print(f"星期：{[Datetime().day_of_week() for _ in range(num)]}")
print(f"时区：{[Datetime().gmt_offset() for _ in range(num)]}")
print(f"频率：{[Datetime().periodicity() for _ in range(num)]}")
print(f"时间戳：{[Datetime().timestamp() for _ in range(num)]}")
print(f"大陆/时区：{[Datetime().timezone() for _ in range(num)]}")
print(f"某年的第多少周：{[Datetime().week_date() for _ in range(num)]}")

print("*" * 50)

print(f"标题/古文句：{[Text(locale=Locale.ZH).title() for _ in range(num)]}")
print(f"句子：{[Text(locale=Locale.ZH).sentence() for _ in range(num)]}")
print(f"词语：{[Text(locale=Locale.ZH).word() for _ in range(num)]}")
print(f"顺序字母：{[Text(locale=Locale.ZH).alphabet() for _ in range(num)]}")
print(f"短回答：{[Text(locale=Locale.ZH).answer() for _ in range(num)]}")
print(f"表情包：{[Text(locale=Locale.ZH).emoji() for _ in range(num)]}")
print(f"程度词：{[Text(locale=Locale.ZH).level() for _ in range(num)]}")
print(f"短句引用：{[Text(locale=Locale.ZH).quote() for _ in range(num)]}")
print(f"中文颜色：{[Text(locale=Locale.ZH).color() for _ in range(num)]}")
print(f"HEX 颜色（十六进制颜色）：{[Text(locale=Locale.ZH).hex_color() for _ in range(num)]}")
print(f"RGB 颜色：{[Text(locale=Locale.ZH).rgb_color() for _ in range(num)]}")

print("*" * 50)

print(f"网址：{[Internet().url() for _ in range(num)]}")
print(f"股票网址：{[Internet().stock_image_url() for _ in range(num)]}")
print(f"IPv4 地址：{[Internet().ip_v4() for _ in range(num)]}")
print(f"IPv4 对象：{[Internet().ip_v4_object() for _ in range(num)]}")
print(f"IPv4 端口：{[Internet().ip_v4_with_port() for _ in range(num)]}")
print(f"IPv6 地址：{[Internet().ip_v6() for _ in range(num)]}")
print(f"IPv6 对象：{[Internet().ip_v6_object() for _ in range(num)]}")
print(f"端口号：{[Internet().port() for _ in range(num)]}")
print(f"内容类别：{[Internet().content_type() for _ in range(num)]}")
print(f"DSN 号：{[Internet().dsn() for _ in range(num)]}")
print(f"公共 DSN 号：{[Internet().public_dns() for _ in range(num)]}")
print(f"用户代理：{[Internet().user_agent() for _ in range(num)]}")
print(f"HOST 名：{[Internet().hostname() for _ in range(num)]}")
print(f"MAC 地址：{[Internet().mac_address() for _ in range(num)]}")
print(f"HTTP 方法：{[Internet().http_method() for _ in range(num)]}")
print(f"HTTP 请求头：{[Internet().http_request_headers() for _ in range(num)]}")
print(f"HTTP 响应头：{[Internet().http_response_headers() for _ in range(num)]}")
print(f"HTTP 状态码：{[Internet().http_status_code() for _ in range(num)]}")
print(f"HTTP 状态消息：{[Internet().http_status_message() for _ in range(num)]}")
print(f"URL 路径：{[Internet().path() for _ in range(num)]}")
print(f"URL 查询参数：{[Internet().query_parameters() for _ in range(num)]}")
print(f"URL 查询字符串：{[Internet().query_string() for _ in range(num)]}")
print(f"URL：{[Internet().slug() for _ in range(num)]}")
print(f"TLD：{[Internet().tld() for _ in range(num)]}")
print(f"TLD 列表：{[Internet().top_level_domain() for _ in range(num)]}")
print(f"URI：{[Internet().uri() for _ in range(num)]}")

print("*" * 50)

print(f"DNA 序列：{[Science().dna_sequence() for _ in range(num)]}")
print(f"RNA 序列：{[Science().rna_sequence() for _ in range(num)]}")
print(f"测量单位：{[Science().measure_unit() for _ in range(num)]}")
print(f"米（单位）的前缀：{[Science().metric_prefix() for _ in range(num)]}")

print("*" * 50)

print(f"：{[Path().user() for _ in range(num)]}")
print(f"：{[Path().home() for _ in range(num)]}")
print(f"：{[Path().root() for _ in range(num)]}")
print(f"：{[Path().dev_dir() for _ in range(num)]}")
print(f"：{[Path().platform for _ in range(num)]}")
print(f"：{[Path().project_dir() for _ in range(num)]}")
print(f"：{[Path().users_folder() for _ in range(num)]}")

print("*" * 50)

print(f"CID 号：{[Payment().cid() for _ in range(num)]}")
print(f"CVV 码：{[Payment().cvv() for _ in range(num)]}")
print(f"比特币地址：{[Payment().bitcoin_address() for _ in range(num)]}")
print(f"信用卡到期日：{[Payment().credit_card_expiration_date() for _ in range(num)]}")
print(f"信用卡类型：{[Payment().credit_card_network() for _ in range(num)]}")
print(f"信用卡卡号：{[Payment().credit_card_number() for _ in range(num)]}")
print(f"信用卡卡号/到期日/持有人信息：{[Payment().credit_card_owner() for _ in range(num)]}")
print(f"以太坊地址：{[Payment().ethereum_address() for _ in range(num)]}")
print(f"Paypal （电子邮箱）账号：{[Payment().paypal() for _ in range(num)]}")

print("*" * 50)

print(f"CPU：{[Hardware().cpu() for _ in range(num)]}")
print(f"CPU 型号：{[Hardware().cpu_codename() for _ in range(num)]}")
print(f"CPU 频率：{[Hardware().cpu_frequency() for _ in range(num)]}")
print(f"CPU 代：{[Hardware().generation() for _ in range(num)]}")
print(f"GPU：{[Hardware().graphics() for _ in range(num)]}")
print(f"生产商：{[Hardware().manufacturer() for _ in range(num)]}")
print(f"手机型号：{[Hardware().phone_model() for _ in range(num)]}")
print(f"手机内存：{[Hardware().ram_size() for _ in range(num)]}")
print(f"Ram 类型：{[Hardware().ram_type() for _ in range(num)]}")
print(f"分辨率：{[Hardware().resolution() for _ in range(num)]}")
print(f"屏幕尺寸：{[Hardware().screen_size() for _ in range(num)]}")
print(f"闪存信息：{[Hardware().ssd_or_hdd() for _ in range(num)]}")

print("*" * 50)

print(f"汽车名称：{[Transport().car() for _ in range(num)]}")
print(f"飞机型号：{[Transport().airplane() for _ in range(num)]}")
print(f"发动机注册号前缀：{[Transport().vehicle_registration_code() for _ in range(num)]}")

print("*" * 50)

print(f"各类文件名和后缀：{[File().file_name() for _ in range(num)]}")
print(f"文件大小：{[File().size(10, 100) for _ in range(num)]}")
print(f"文件后缀：{[File().extension() for _ in range(num)]}")
print(f"文件类型/种类：{[File().mime_type() for _ in range(num)]}")
